import turtle

shiva=turtle.Turtle()
shiva.speed(1)
shiva.color("blue","green")
#shiva.forward(100)
#shiva.left(190)
#shiva.forward(200)
#shiva.right(34)
#shiva.forward(40)

#for  square in the plane
shiva.begin_fill()
shiva.forward(100)
shiva.left(90)
shiva.forward(100)
shiva.left(90)
shiva.forward(100)
shiva.left(90)
shiva.forward(100)
shiva.end_fill()
shiva.penup()
shiva.forward(10)
#second one
shiva.color("blue","cyan")
shiva.pendown()
shiva.begin_fill()
shiva.forward(100)
shiva.left(90)
shiva.forward(100)
shiva.left(90)
shiva.forward(100)
shiva.left(90)
shiva.forward(100)
shiva.end_fill()
turtle.done()
