from turtle import *
import turtle
shiva=turtle.Turtle()
shiva.speed(1)
shiva.color("blue","green")
#shiva.forward(100)
#shiva.left(190)
#shiva.forward(200)
#shiva.right(34)
#shiva.forward(40)

#for  square in the plane
shiva.begin_fill()

shiva.left(90)
shiva.forward(25)
shiva.left(90)
shiva.forward(35)
shiva.right(90)
shiva.forward(200)
shiva.right(90)
shiva.forward(35)
shiva.left(90)
shiva.forward(25)
shiva.left(90)
shiva.forward(100)
shiva.left(90)
shiva.forward(25)
shiva.left(90)
shiva.forward(35)
shiva.right(90)
shiva.forward(200)
shiva.right(90)
shiva.forward(35)
shiva.left(90)
shiva.forward(25)
shiva.left(90)
shiva.forward(100)
shiva.end_fill()
shiva.penup()
shiva.forward(150)
shiva.pendown()
#heart
def curvemove():
    for i in range(200):
        shiva.right(1)
        shiva.forward(1.2)
shiva.speed(1)
shiva.color("blue","red")       
shiva.begin_fill()
shiva.left(140)
shiva.forward(131.65)
curvemove()
shiva.left(120)
curvemove()
shiva.forward(131.65)
shiva.end_fill()
#U only the one
shiva.penup()
shiva.right(200)
shiva.forward(250)
turtle.done()
